apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: stonesoup-devfile-sample-code-with-quarkus-iuut
  namespace: btison-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:449eb9f481fc026c095c0caed5e9f4cae171f2f5366c8d85189d34fb251372bb
        name: my-java-quarkus
        resources: {}
status: {}
