apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-devfile-sample-code-with-quarkus-iuut
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-devfile-sample-code-with-quarkus-iuut
    app.kubernetes.io/part-of: my-quarkus-app
  name: stonesoup-devfile-sample-code-with-quarkus-iuut
  namespace: btison-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: stonesoup-devfile-sample-code-with-quarkus-iuut
    weight: null
status: {}
