apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-devfile-sample-code-with-quarkus-iuut
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-devfile-sample-code-with-quarkus-iuut
    app.kubernetes.io/part-of: my-quarkus-app
  name: stonesoup-devfile-sample-code-with-quarkus-iuut
  namespace: btison-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: stonesoup-devfile-sample-code-with-quarkus-iuut
status:
  loadBalancer: {}
